apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v1
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: web-v1
  template:
    metadata:
      labels:
        app: web-v1
    spec:
      containers:
        - name: web-v1
          image: ianwong22/microblog:lastest
          env:
           - name: SQLALCHEMY_DATABASE_URI
             value: ""
          ports:
            - name: tcp
              containerPort: 80
