---
apiVersion: v1
kind: Service
metadata:
  name: web-v1-private
  namespace: default # This is the default namespace
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: web-v1
  ports:
    - name: http
      port: 80
      targetPort: 80