---
apiVersion: v1
kind: Service
metadata:
  name: web-v1-private
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: web-v1
  ports:
    - port: 80
      targetPort: tcp